{{- if .Values.app.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-app.fullname" . }}-secrets
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.app.secrets }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
{{- end }}
